# Generated by Django 5.0.6 on 2024-05-20 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='subject',
            new_name='Subject',
        ),
    ]
