# Generated by Django 5.0.6 on 2024-05-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_playername_sports_playername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
